import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: [
    'typescript',
    'react',
    'jsx-a11y',
    'import',
    'vitest',
    'unicorn',
    'oxc',
  ],
  jsPlugins: [
    {
      name: '@convex-dev',
      specifier: '@convex-dev/eslint-plugin',
    },
    {
      name: 'anti-slop',
      specifier: './tools/oxlint/anti-slop/index.ts',
    },
    {
      name: 'anti-slop-effect',
      specifier: './tools/oxlint/anti-slop/effect/index.ts',
    },
  ],
  options: {
    typeAware: true,
  },
  ignorePatterns: [
    '.agent/**',
    '.agents/**',
    'agent/skills/**',
    '.claude/**',
    '.codex/**',
    '.continue/**',
    'convex/_generated/**',
    '.cursor/**',
    '.gemini/**',
    '.opencode/**',
    '.pi/**',
    '.roo/**',
    '.windsurf/**',
    'src/routeTree.gen.ts',
    'tools/oxlint/anti-slop/**',
    '.output/**',
    '.tanstack/**',
    '.convex/**',
    'dist/**',
    'node_modules/**',
  ],
  rules: {
    eqeqeq: 'error',
    'no-console': 'warn',
    'require-yield': 'off',
    'typescript/consistent-type-imports': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-misused-spread': 'error',
    'typescript/no-misused-promises': 'error',
    'typescript/no-non-null-assertion': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'anti-slop/no-chained-type-assertions': 'error',
    'anti-slop/no-conditional-empty-object-spread': 'error',
    'anti-slop/no-known-value-widening': 'error',
    'anti-slop/no-module-mocking': 'error',
    'anti-slop/no-object-parameters': 'error',
    'anti-slop/no-reflect-apply': 'error',
    'anti-slop/no-reflect-get': 'error',
    'anti-slop/no-runtime-typeof': 'error',
    'anti-slop/no-shape-in-symbol-names': 'error',
    'anti-slop/no-unknown-parameters': 'error',
    'anti-slop/no-unknown-returns': 'error',
    'anti-slop/no-unknown-type-aliases': 'error',
    'anti-slop/no-unsafe-dictionary-type': 'error',
    'anti-slop/no-widen-then-assert': 'error',
    'anti-slop/require-safety-comment-for-type-assertion': 'error',
    'anti-slop-effect/no-service-constructor-imports': 'error',
  },
  overrides: [
    {
      files: ['convex/**/*.ts'],
      rules: {
        '@convex-dev/import-wrong-runtime': 'off',
        '@convex-dev/no-old-registered-function-syntax': 'error',
        '@convex-dev/require-args-validator': 'error',
        '@convex-dev/explicit-table-ids': 'error',
        '@convex-dev/no-filter-in-query': 'error',
        '@convex-dev/no-collect-in-query': 'error',
        '@convex-dev/no-top-of-hour-crons': 'warn',
        '@convex-dev/no-schema-import-cycle': 'error',
      },
    },
  ],
})
