/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LabRouteImport } from './routes/lab'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBookmarksRouteImport } from './routes/_app.bookmarks'
import { Route as AppInboxRouteImport } from './routes/_app.inbox'
import { Route as PlaygroundMaterialsAsciiRouteImport } from './routes/playground_.materials.ascii'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookmarksRoute = AppBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const PlaygroundMaterialsAsciiRoute =
  PlaygroundMaterialsAsciiRouteImport.update({
    id: '/playground_/materials/ascii',
    path: '/playground/materials/ascii',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/lab': typeof LabRoute
  '/playground': typeof PlaygroundRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/inbox': typeof AppInboxRoute
  '/playground/materials/ascii': typeof PlaygroundMaterialsAsciiRoute
}
export interface FileRoutesByTo {
  '/lab': typeof LabRoute
  '/playground': typeof PlaygroundRoute
  '/bookmarks': typeof AppBookmarksRoute
  '/inbox': typeof AppInboxRoute
  '/': typeof AppIndexRoute
  '/playground/materials/ascii': typeof PlaygroundMaterialsAsciiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/lab': typeof LabRoute
  '/playground': typeof PlaygroundRoute
  '/_app/bookmarks': typeof AppBookmarksRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/': typeof AppIndexRoute
  '/playground_/materials/ascii': typeof PlaygroundMaterialsAsciiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lab'
    | '/playground'
    | '/bookmarks'
    | '/inbox'
    | '/playground/materials/ascii'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/lab'
    | '/playground'
    | '/bookmarks'
    | '/inbox'
    | '/'
    | '/playground/materials/ascii'
  id:
    | '__root__'
    | '/_app'
    | '/lab'
    | '/playground'
    | '/_app/bookmarks'
    | '/_app/inbox'
    | '/_app/'
    | '/playground_/materials/ascii'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LabRoute: typeof LabRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PlaygroundMaterialsAsciiRoute: typeof PlaygroundMaterialsAsciiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookmarks': {
      id: '/_app/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AppBookmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/playground_/materials/ascii': {
      id: '/playground_/materials/ascii'
      path: '/playground/materials/ascii'
      fullPath: '/playground/materials/ascii'
      preLoaderRoute: typeof PlaygroundMaterialsAsciiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBookmarksRoute: typeof AppBookmarksRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookmarksRoute: AppBookmarksRoute,
  AppInboxRoute: AppInboxRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LabRoute: LabRoute,
  PlaygroundRoute: PlaygroundRoute,
  PlaygroundMaterialsAsciiRoute: PlaygroundMaterialsAsciiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
